"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['sand.py']
DATA_FILES = ['icon.ico', 'client.py', 'resources.py', 'date.py', 'README.md',
              'requirements.txt']
OPTIONS = {
        'iconfile': 'icon.icns'
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
